SELECT I.ITEM_ID,
        I.ITEM_NAME,
        I.RARITY
FROM ITEM_INFO I
JOIN (
    SELECT T.ITEM_ID,
            T.PARENT_ITEM_ID,
            II.RARITY
    FROM ITEM_TREE T
    JOIN ITEM_INFO II
    ON T.PARENT_ITEM_ID = II.ITEM_ID
    WHERE II.RARITY = "RARE"
    ) J
ON I.ITEM_ID = J.ITEM_ID
ORDER BY I.ITEM_ID DESC;